# Generated by Django 2.0.2 on 2018-08-16 13:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profilemod',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='nikname',
            new_name='nickname',
        ),
    ]
